name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run install
      run: make install

    - name: Run test
      run: make test
